### ISSUE TITLE
Operator name bikeshedding

### ISSUE THREAD

**Issue by js-choi** [tabatkins/proposal-call-operator#1]
This is a bit pedantic, but I think that we might want to call this `…::(…)` operator something like the “call-this operator”, “call-on operator”, or something instead of “call operator”. 

The existing `…(…)` syntax is already known as the “call operator” today. For the sake of learners (and also for developers in general trying to communicate with each other), I think that we should try to distinguish the name of `…::(…)` from the name of `…(…)`.

(“Call-this” is similar to [“bind-this”](https://github.com/tc39/proposal-bind-this), but that shouldn’t be a problem in the end, because call-this and bind-this are mutually exclusive; only one of them would ever get added to JavaScript.)

**Comment by tabatkins** [comment]
Fair, I'm okay with "call-this"
